---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: certsigner-envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: certsigner-envoy
  template:
    metadata:
      labels:
        app: certsigner-envoy
    spec:
      volumes:
        - name: dex-config
          configMap:
            name: dex-config
        - name: envoy-config
          configMap:
            name: envoy-config
      containers:
        - name: dex
          image: ghcr.io/dexidp/dex:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: dex
              containerPort: 5556
              protocol: TCP
          volumeMounts:
            - name: dex-config
              mountPath: /etc/dex/config.docker.yaml
              subPath: config.docker.yaml
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 64Mi
              cpu: 50m
        - name: envoy
          image: ghcr.io/ctyano/certsigner-envoy:latest
          imagePullPolicy: IfNotPresent
          command:
            - envoy
            - -c
            - /etc/envoy/envoy.yaml
            - -l
            - debug
          ports:
            - containerPort: 10000
          volumeMounts:
            - name: config
              mountPath: /etc/envoy/envoy.yaml
              subPath: envoy.yaml
