---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: athenz

resources:
  - deployment.yaml
  - namespace.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: envoy-config
    files:
      - envoy.yaml=./envoy.yaml
